Complete services
swrggv/java-explore-with-me pull request #1
Opened 2022-10-30 21:52 UTC by swrggv

2022-11-02 11:07 UTC, eugene-lenkevich requested changes
Привет, Александра, спасибо за PR

Первым делом поздравляю тебя с тем, что ты дошла до дипломной работы, ты крута, тут без вариантов :)

Далее, 
наша цель в том, чтобы сделать красоту в этом проекте, все таки диплом, вдруг по нему будут оценивать навыки. Я оставил кучку коментариев, будут любые вопросы, задавай в слаке, не стесняйся, немножко допилить осталось :)

Удачи!

2022-11-02 11:07 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/EwmConfig.java
> +    @Value("yyyy-MM-dd")
Эта аннотация нужна чтобы вытащить значение из настроек, в  таком виде это тот же хардкод только усложненный :)
можно сделать вот так
`@Value("${ewm.date.format:yyyy-MM-dd}")`

где ewm.date.format - название настройки, но если она не указана то будет браться значение по умолчанию - yyyy-MM-dd

2022-11-02 11:07 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/category/CategoryRepository.java
> +@Repository
Эту аннотацию вроде как можно не писать, и так должно работать :)

2022-11-02 11:07 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/category/CategoryRepository.java
> +    Boolean existsCategoriesByName(@Param("name") String name);
Это работать будет и даже, но модно сделать чутка покороче :) 
@Query руками можно не писать в таком случае, достаточно написать правильный метод и все будет работать автоматически, вот как то так

`Boolean existsByName(String name);`

https://www.baeldung.com/spring-data-exists-query

2022-11-02 11:07 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/category/CategoryServiceImpl.java
> +        Optional<Category> category = categoryRepository.findById(idCategory);
Тут тоже можно сделать запись короче, без явных проверок (if)

`Category category =  categoryRepository.findById(idCategory).orElseThrow(()->  new ModelNotFoundException .... )`

2022-11-02 11:07 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/compilation/dto/NewCompilationDto.java
> +    private List<Long> events = new ArrayList<>();
private Collection<Long> events = ...а тут любая коллекция :)

А так наверно да, лучше будет Set или даже LinkedHashSet если требуется сохранить порядок
А можно вместо чисел и сами dto скложить, в отладке проще, но это смоотри сама, не так чтобы критично :)

2022-11-02 11:07 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/event/EventAdminController.java
> +                LocalDateTime.parse(rangeStart, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")),
`LocalDateTime.parse(date, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))`

Вот это лучше вынести в отдельный метод, как минимум тут дулирование.

А еще лучше, конечно, сразу объявить тип переменных LocalDateTime чтобы потом не возится с ручным пасингом  :)

2022-11-02 11:07 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/event/EventPrivateController.java
> +    public EventPrivateController(EventService eventService, ParticipationService participationService) {
Это кстати можно заменить на аннотацию @RequiredArgsConstructor и не писать конструкторв ручками :)

2022-11-02 11:07 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/event/EventRepository.java
> +    List<Event> findByInitiator(@Param("userId") long userId, Pageable pageable);
В данном случае метод работать будет и так, без указания @Query :)

2022-11-02 11:07 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/event/dto/NewEventDto.java
> +    //@Max(groups = Create.class, value = 2000, message = "Annotation can not be more then 2000 characters")
Закомментированный код не стоит оставлять, толку от него никакого :)

2022-11-02 11:07 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/participants/ParticipationRepository.java
> +    List<ParticipationRequest> findAllParticipantsRequest(@Param("eventId") long eventId,
Опять таки, @Query тут не обязателен

Я бы сделал как то вот так

 List<ParticipationRequest> findAllByEventAndStatus(Event event, Status status)

передаю в метод сущность события а не ее идентификатор. С одной стороны, со стороны производительности, это не очень, так как возможно в генерируемом sql будет лишний join (но это не точно надо проверять какой запрос там генерируется, может хибер его и оптимизирует для таких простых случаев). Однако, с концептуальной стороны это более правильно, мы же так можем передать любой ид, а тут же есть хоть какая то гарантия что передадим ид сущестующей сущности. И, так же, самое главное, в этом случае мы оперируем сущностями предметной области, а не какими то абстрактными числами, так мы делаем наш код проще. Не надо оптимизировать код заранее :)

2022-11-02 11:07 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/client/Client.java
> +public interface Client {
Вот тут я предложу следующее улучшение, не обязательно, но если сделаешь то код будет гораздо круче выглядеть.

В stats делаем интерфейс c этими же аннотациями

```
public interface ClientApi {
    @RequestMapping(method = RequestMethod.POST, value = "/hit")
    void hit(@RequestBody EndpointHit endpointHit);

    @RequestMapping(method = RequestMethod.GET, value = "/stats")
    List<ViewStats> stats(@RequestParam String start,
                          @RequestParam String end,
                          @RequestParam(required = false) List<String> uris,
                          @RequestParam(defaultValue = "false") Boolean unique);
}
```

мы от него будем наследовать и фейн-клиент и сам контроллер, методы же у нас и там и там одинаковые (одинкаовые же =).

Это все у нас переезжает в stats. Далее возможны варианты:
а) попроще: подключаем к первому модулю модуль stats
б) чутка сложней, но правильно: контракты сервиса stats, dto и фейн-клиент, мы перекладываем в новый модуль stats-api и подключаем  к обоим сервисам

Так обеспечивается соответствие API. В первом сервисе мы просто инжектим фейн-клиент, и просто вызываем его методы, все остальное от нас сокрыто, не надо возится с настройками и API, не надо знать даже по каким реальным uri работают наши методы, в теории, они всегда у нас те что надо :)

2022-11-02 15:26 UTC, swrggv commented on ewm/src/main/java/ru/practicum/ewm/client/Client.java
> +public interface Client {
вот это прям круто, спасибо за идею. сейчас малодушно сделала первый вариант), но потом скорее всего допишу еще один модуль

2022-11-02 15:27 UTC, swrggv commented on ewm/src/main/java/ru/practicum/ewm/compilation/dto/NewCompilationDto.java
> +    private List<Long> events = new ArrayList<>();
когда нибудь я не забуду удалить закомментированные разговоры сама с собой)

2022-11-02 16:42 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/client/Client.java
> +public interface Client {
Для учебного проекта это не так важно, но для общего развития лучше помнить как может получится 

Есть такой антипаттерн - "распределенный монолит", главное избежать этой ситуации. 

https://gist.github.com/r3code/39a6429b5fe0c2aa3f91851b878d202e

![image](https://user-images.githubusercontent.com/94845100/199548991-082eba76-4484-49a8-aa12-58e8449ee872.png)

То есть, в целом, лучше ничего лишнего не подключать, рано или поздно кто-то возьмет да и потащит что-то из соседнего сервиса. А вот если мы импортируем только модуль с контрактами, то доменные модели остаются изолированными :)

2022-11-03 10:45 UTC, swrggv commented on ewm/src/main/java/ru/practicum/ewm/client/Client.java
> +public interface Client {
перенесла ClientApi в stats и от него наследовалась, в модуле ewm прописала зависимость от модуля stats, все рпекрасно работало, тесты проходили, но приложение не собиралось. Билась сутки и в итоге пришлось вернуть как было(

2022-11-03 11:29 UTC, eugene-lenkevich approved these changes
Привет, спасибо за доработку

Стало заметно компактней,  то что с модулями возникли затруднения не критично, до идеала можно долго доводить, главное - то что дипломная работа выглядит солидно, все отлично  :)

2022-11-03 11:29 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/event/model/Location.java
> -    private float lat; //широта
Эти коменты как раз можно было б и оставить, кажется, что те кто не касался этой предметной области и не сообразят сразу что это :)

2022-11-03 11:33 UTC, merged